apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frontendservice-operator-role
rules:
- apiGroups: ["mycompany.com"]
  resources: ["frontendservices"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
